### ISSUE TITLE
KeyError: 'documents'

### ISSUE THREAD

**Issue by iseemasaharan** [twitterdev/weekly-tweet-sentiment#2]
Everything is working fine, but on this line, I am getting an error. 
langs = pd.DataFrame(with_languages["documents"])

**Comment by JessicaGarson** [comment]
Thanks for reaching out. Which file are you using?

**Comment by JessicaGarson** [comment]
The most recent version of this code is [here](https://github.com/twitterdev/weekly-tweet-sentiment) using v2 of the Twitter API which does not seem to contain this line.

**Comment by iseemasaharan** [comment]
Okay, thank you.
